version: "3.9"

services:
  rest_server_authentication:
    build:
      context: .
    ports:
      - "8000:5000"

  rest_server_master_data:
    build:
      content:
        ports:
          - "8000:5000"

  rest_server_message_queues:
    build:
      content:
        ports:
          - "8000:5000"

  rest_server_calculations:
    build:
      content:
        ports:
          - "8000:5000"









